### ISSUE TITLE
功能请求：自定义爆破点，实时显示结果

### ISSUE THREAD

**Issue by duokebei** [0x2E/sf#15]
作者您好，想提点功能建议，烦请作者查看，不胜感激
1、有时碰到一种资产多的域名，会有很多测试的域名，例如：test-api.baidu.com、test-mall.baidu.com，其中api和mall这两个的位置，可以作为一个自定义设置的爆破点。
2、显示方面：一个是可不可以加一个每爆破出一个结果，就将该子域名显示在屏幕上，当然可以添加一个参数对其进行控制是否显示在屏幕上；有个进度条百分比显示更完美啦

感谢阅读

**Comment by 0x2E** [comment]
很好的建议，这两点后续都会考虑，感谢反馈

**Comment by 0x2E** [comment]
1. [v0.4.0](https://github.com/0x2E/sf/releases/tag/v0.4.0) 加了自定义爆破点，可以试试
2. 现在默认输出结果和运行日志，如果只想看结果的话可以用 `--silent` 参数
